name: Build version

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        options:
          - major
          - minor
          - patch
        default: patch
        description: Choose what to bump.


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: echo input
        run: |
          echo "bump: ${{ inputs.bump }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Bump version in package.json
        run: npm version ${{ inputs.bump }}

      - name: Build extension vsix file
        run: |
          npm install --global @vscode/vsce
          vsce package

      - name: Upload vsix file as attachment to this job
        uses: actions/upload-artifact@v3
        with:
          path: ./*.vsix
          name: vsix

      - name: Push package.json with bumped version
        run: git push
        