name: Build and upload vsix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    strategy:
      matrix:
        include:
          - platform: darwin
            arch: x64
          - platform: darwin
            arch: arm64
          - platform: linux
            arch: x64
          - platform: linux
            arch: arm64
          - platform: win32
            arch: x64
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: './.github/actions/setup'

      - name: Validate release
        run: |
          npm run tsc
          npm run lint
          npm run build
          rm -rf out/

      - name: Set PRERELEASE version
        run: |
          current_version=$(jq -r '.version' package.json)
          short_sha=$(git rev-parse --short HEAD)
          jq --arg new_version "${current_version}-PRERELEASE-${short_sha}" '.version = $new_version' package.json > tmp.json
          mv tmp.json package.json

      - name: Build extension vsix file
        run: |
          npm install --global @vscode/vsce
          npm run updatedocs
          npm run updatecwf
          vsce package
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.CODESCENE_IDE_DOCS_AND_WEBVIEW_TOKEN }}

      - name: Upload vsix artifact
        uses: actions/upload-artifact@v4
        with:
          path: 'codescene-vscode-test-*-${{ matrix.platform }}-${{ matrix.arch }}.vsix'
          name: 'codescene-vscode-test-prerelease-${{ matrix.platform }}-${{ matrix.arch }}'
