name: Build and upload vsix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    strategy:
      matrix:
        include:
          - platform: darwin
            arch: x64
          - platform: darwin
            arch: arm64
          - platform: linux
            arch: x64
          - platform: linux
            arch: arm64
          - platform: win32
            arch: x64
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: './.github/actions/setup'

      - name: Validate release
        run: |
          npm run tsc
          npm run lint
          npm run build
          rm -rf out/

      - name: Set PRERELEASE version
        run: |
          current_version=$(jq -r '.version' package.json)
          short_sha=$(git rev-parse --short HEAD)
          jq --arg new_version "${current_version}-PRERELEASE-${short_sha}" '.version = $new_version' package.json > tmp.json
          mv tmp.json package.json

      - name: Install vsce
        run: npm install --global @vscode/vsce

      - name: Package platform-specific VSIX
        run: node ./scripts/package-platform.js ${{ matrix.platform }} ${{ matrix.arch }}
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.CODESCENE_IDE_DOCS_AND_WEBVIEW_TOKEN }}

      # .cs-prod-build is expected for correct functioning of the extension, so we validate its presence:
      - name: Verify .cs-prod-build marker in VSIX
        run: |
          VSIX_FILE=$(ls codescene-vscode-*-${{ matrix.platform }}-${{ matrix.arch }}.vsix)
          unzip -l "$VSIX_FILE" | tee vsix-contents.txt
          if grep -q "\.cs-prod-build" vsix-contents.txt; then
            echo ".cs-prod-build marker found in VSIX"
            exit 0
          else
            echo ".cs-prod-build marker not found in VSIX!"
            exit 1
          fi

      - name: Upload vsix artifact
        uses: actions/upload-artifact@v4
        with:
          path: 'codescene-vscode-*-${{ matrix.platform }}-${{ matrix.arch }}.vsix'
          name: 'codescene-vscode-prerelease-${{ matrix.platform }}-${{ matrix.arch }}'
